title = "go-login config file"

[Common]
ListenPort = 7788
EnableRedisCache = false
EnableLocalCache = false
MinPasswordLength = 8
MaxUsernameLen = 30
HomePage = "home.html"
LoginPage = "login.html"
RegistPage = "regist.html"
EnterPage = "login_regist.html"
PasswordComplexitys = ["lower", "upper", "digit", "spec"]



[Redis]
Addr = "localhost:6379" # redis

[MySQL]
Addr = "lijunshi:lijunshipwd@tcp(localhost:3306)/users"
MaxIdle = 2
MaxConn = 10
ShowSQL = false
LogLevel = 1

[Session]
TTL = 900
Key = "sess_"

[SQL]
File = "./db.sql"

[Blacklist]
IPList = ["10.10.40.12", "10.10.40.13"]
UsernameList = ["lijunshi22", ]

[RateLimit]
KeyPrefix = "Ratelimit-"
Limit = 10 # 一分钟限制的请求数
Mode = "redis"